version: "2"
networks:
  ca_net:
    external: false
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"
services:
  savopkrill.com:
    image: krill
    container_name: ca
    cap_add:
      - NET_ADMIN
    volumes:
      - ./add_info.py:/var/krill/add_info.py
      - ./logs/krill.log:/var/krill/logs/krill.log
      - ./logs/rsync.log:/var/krill/logs/rsync.log
      - ./krill.sh:/var/krill/start.sh
      - ./configs/krill/krill.conf:/var/krill/data/krill.conf
      - ./configs/krill/rsyncd.conf:/etc/rsyncd.conf
      - ./nodes/roas.json:/var/krill/roas.json
      - ./nodes/aspas.json:/var/krill/aspas.json
      - ./configs/krill/keys/web/cert.pem:/var/krill/data/ssl/cert.pem
      - ./configs/krill/keys/web/key.pem:/var/krill/data/ssl/key.pem
      - ./configs/krill/keys/ca/cert.pem:/usr/local/share/ca-certificates/extra/ca.crt
    networks:
      ca_net:
        ipv4_address: 10.10.0.2
    command: >
      bash /var/krill/start.sh
  roa:
    image: routinator
    container_name: roa
    cap_add:
      - NET_ADMIN
    networks:
      ca_net:
        ipv4_address: 10.10.0.3
    depends_on:
      - savopkrill.com
    volumes:
      - ./configs/routinator.conf:/etc/routinator/routinator.conf
      - ./logs/routinator.log:/var/routinator/logs/routinator.log
      - ./configs/krill/keys/ca/cert.pem:/usr/local/share/ca-certificates/extra/ca.crt
      - ./configs/krill/keys/web/cert.pem:/var/routinator/data/web.pem
      - ./configs/krill/keys/ca/cert.pem:/var/routinator/data/ca.pem
      - ./routinator.sh:/var/routinator/start_routinator.sh
    ports:
        - "8323:8323"
        - "9556:9556"
    command: >
      bash /var/routinator/start_routinator.sh
